### PR TITLE
Create core.py

### PR DESCRIPTION
**Pull request by AlexanderMarobe**
sdew eqw

### CODE REVIEW

**Comment by RobertGoodman08** [comment]
python

**Comment by AlexanderMarobe** [comment]
ok

**Comment by RobertGoodman08** [comment]
> Ok

yest

**Comment by AlexanderMarobe** [comment]
> > Ok
> 
> yest

k

**Comment by AlexanderMarobe** [comment]
django

**Comment by RobertGoodman08** [comment]
> Джанго

jion

**Pull request merged**
